### ISSUE TITLE
Got error `StripeCheckout is not defined`

### ISSUE THREAD

**Issue by williamchong007** [jofftiquez/vue-stripe-checkout#15] opened 2018-05-09 07:46 UTC
I use sentry for our production issue tracking, and I got like around 100s of this error 
Any suggestions on how to figure out if theres anything wrong?

![image](https://user-images.githubusercontent.com/6198816/39802159-e521d6a4-539f-11e8-8c8c-77a45b60c584.png)

**Comment by jofftiquez** [comment] 2018-05-09 10:16
Hi @williamchong007 does sentry run the code in a headless browser or anything similar to simulate the code?

**Comment by jofftiquez** [comment] 2018-05-09 10:41
@williamchong007 wow that's nice! Hm that's weird tho, maybe I need to upgrade my code.

**Comment by jofftiquez** [comment] 2018-05-09 10:43
@williamchong007 But does this plugin work even with those errors?

**Comment by williamchong007** [comment] 2018-05-09 12:28
@jofftiquez As far as we tested, this plugin is working for all of our testers without such error
It is just not loading at all for those other users I guess

**Comment by jofftiquez** [comment] 2018-05-10 07:32
@williamchong007 maybe it's related to the browser or browser version? Let's dig in deeper.

**Comment by williamchong007** [comment] 2018-05-11 05:31
I think it is on some rare case `checkout.js` is not loaded properly, but the script doesnt quite know nor handled that

**Comment by jofftiquez** [comment] 2018-05-11 06:58
@williamchong007 that's a good starting point. Thanks! I will check this.

**Comment by diegovdc** [comment] 2018-05-23 19:10
I have got the same issue in dev.  Apparently the problem lies in `src/index.js` line `106`. It seems that the `setTimeout` maybe to too short for some internet connections, or because of lags on the web.

Thats why sometimes StripeCheckout does not yet exist. I can confirm that on the second try it works as expected.  

Maybe use an interval instead to periodically check?

**Comment by jofftiquez** [comment] 2018-05-24 08:09
Hi @diegovdc I think you're referring to #12. But thanks a lot for the feedback!

**Comment by diegovdc** [comment] 2018-05-24 14:10
Perhaps it is related. But I am pretty sure I was getting the "StripeCheckout is not defined" message because the script was not being loaded on time. 

You might be able to reproduce it just by using a shorter timeout. Or better yet by using the "network throttle" function in a chrome browser.

**Comment by jofftiquez** [comment] 2018-05-24 16:39
@diegovdc Ooooh I see. The only problem with the snippet I created was that if the internet is slow the checkout box will not show immediately. Anyhow, thanks for the feedback, I'm working on a new version right now, I'll keep those suggestions of yours in mind. Hoping to close this soon. Thanks!

**Comment by RoraxHan** [comment] 2018-06-11 07:34
I'm using cdn for this library. 
Any update for this error?

**Comment by jofftiquez** [comment] 2018-06-12 03:41
Will work on this soon. PRs are also welcome.

**Closed** 2018-06-21 09:51 UTC
Labels: bug, review

**Comment by jofftiquez** [comment] 2018-06-21 09:53
Please confirm if this still exits after `1.0.6`

**Comment by sonicfive** [comment] 2018-09-28 00:52
I have this issue on a live server. It works fine on dev. I am getting "StripeCheckout is not defined"
What do you think I should look for?

**Comment by rocchidavide** [comment] 2018-10-21 14:39
I have the same error sometimes

**Comment by jofftiquez** [comment] 2018-10-21 15:32
Hi all, I've been busy this past months, sorry to keep these issues hanging. I promise to get back on them soon. Thank you for you patience and support. Happy Coding to all.

**Comment by JonasJW** [comment] 2019-04-06 14:50
Yep same error and can't get it to work. Any updates?

**Comment by raykudo** [comment] 2019-05-13 03:11
Hello there, I still get this error ver [code]^1.2.6[/code]

**Comment by pathum-kalhan** [comment] 2019-06-23 09:40
I've got the exact same error. My problem was I use this in two different components. But I forgot to change the `ref="checkoutRef"` One place I changed this to `ref="checkoutRef2"`. Then that's it. Problem got solved for me. I think this should mention in the docs as well. Because junior developer like me might not know this `ref` thing.

**Comment by jofftiquez** [comment] 2019-06-23 11:07
@pathum-kalhan thank you. I will do that.
